name: Hello World PowerShell

on:
  push:
    branches:
      - master  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Run PowerShell script
      run: |
        Write-Host "Hello, World!"

